apiVersion: v1
kind: Service
metadata:
  name: nginx-np-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: nginx-port
      protocol: TCP
      port: 32000
      targetPort: 80
      nodePort: 30000
