apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod-01
spec:
  containers:
  - name: myctr
    image: busybox
    command: ['sh','-c','echo $(MY_VAL) && sleep 3600']
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: literal-config
