apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: hello-job
spec:
  parallelism: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - Hello Job for this day
        image: busybox
        name: hello-job
        resources: {}
      restartPolicy: Never
status: {}
