apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webs
  name: webs
spec:
  nodeSelector:
    nodeName: nginxnode
  containers:
  - image: nginx
    name: webs
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
