apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx5
  name: nginx5
spec:
  containers:
  - image: nginx
    name: nginx5
    volumeMounts:
      - name: myvol
        mountPath: /etc/data
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: pvc1
