apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: myctr
    image: busybox
    command: ['sh', '-c', 'echo $(MY_SECRET) & sleep 3600']
    env:
     - name: MY_SECRET
       valueFrom:
         secretKeyRef:
           name: mysecret
           key: username
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
  volumes:
    - name: secret-volume
      secret: 
              secretName: mysecret
