apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod5
  name: pod5
spec:
  nodeSelector:
    env: prod
  containers:
  - image: nginx
    name: pod5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
